# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastserver', '0002_person_programinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programinfo',
            options={'permissions': [('can_edit_programinfo_settings', 'Can edit program info settings')]},
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='category',
            field=models.CharField(choices=[('Sports & Recreation', 'Sports & Recreation'), ('Religion & Spirituality', 'Religion & Spirituality'), ('News & Politics', 'News & Politics'), ('Government & Organizations', 'Government & Organizations'), ('Education', 'Education'), ('Games & Hobbies', 'Games & Hobbies'), ('Science & Medicine', 'Science & Medicine'), ('Arts', 'Arts'), ('Health', 'Health'), ('Comedy', 'Comedy'), ('Technology', 'Technology'), ('Kids & Family', 'Kids & Family'), ('Business', 'Business'), ('Music', 'Music'), ('TV & Film', 'TV & Film'), ('Society & Culture', 'Society & Culture')], max_length=20),
        ),
    ]
