# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastserver', '0003_auto_20170731_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Government & Organizations', 'Government & Organizations'), ('Games & Hobbies', 'Games & Hobbies'), ('Society & Culture', 'Society & Culture'), ('Music', 'Music'), ('Science & Medicine', 'Science & Medicine'), ('Technology', 'Technology'), ('Education', 'Education'), ('Business', 'Business'), ('News & Politics', 'News & Politics'), ('TV & Film', 'TV & Film'), ('Sports & Recreation', 'Sports & Recreation'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Arts', 'Arts'), ('Health', 'Health'), ('Kids & Family', 'Kids & Family')], max_length=20),
        ),
    ]
