name: Build and deploy Python app to Azure Web App - nordicusv-survey

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  
  # For when triggering it manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u fribyte -p ${{ secrets.FRIBYTE_DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f Dockerfile -t fribyte/srib-podcast:latest \
            --build-arg ENVIRONMENT="Production" .

      - name: Push image to Docker Hub
        run: docker push fribyte/srib-podcast:latest
